baseURL = "www.chen.ist"
languageCode = "en-us"
theme = "hugo-serif-theme"
themesDir = "../.."
title = "CHENIST Proactive Cybersecurity"
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
[[menu.main]]
name = "Services"
url = "/services/"
weight = 1
[[menu.main]]
name = "Resources"
url = "/resources/"
weight = 2
[params]
google_analytics_id = ""
google_tag_manager_id = ""
[params.homepage_meta_tags]
meta_description = "Your Proactive Cybersecurity Partner"
meta_og_description = ""
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
meta_og_title = "CHENIST "
meta_og_type = "website"
meta_og_url = "https://chen.ist"
meta_twitter_card = "summary"
meta_twitter_creator = "@chenistsec"
meta_twitter_site = "@chenistsec"
[params.logo]
alt = "CHENIST Proactive Cybersecurity"
mobile = "/images/logo.png"
standard = "/images/logo.png"
